apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  namespace: ollama
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/k3s-home/ollama