apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
  namespace: home-assistant
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/k3s-home