apiVersion: v1
kind: PersistentVolume
metadata:
  name: wyoming-piper-pv
  namespace: wyoming-piper
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/k3s-home