apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper-pvc
  namespace: wyoming-whisper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi