apiVersion: v1
kind: PersistentVolume
metadata:
  name: wyoming-whisper-pv
  namespace: wyoming-whisper
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/k3s-home