apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  namespace: pihole
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/k3s-home/pihole